DOMAIN = "arso_weather_integration"
DEFAULT_NAME = "ARSO Weather Integration"
API_URL = "https://vreme.arso.gov.si/api/1.0/location/"
LOCATIONS_URL = "https://vreme.arso.gov.si/uploads/probase/www/fproduct/json/sl/locations.json"

# example: https://meteo.arso.gov.si/uploads/probase/www/observ/surface/text/sl/observationAms_KREDA-ICA_latest.rss
# Mapping med lokacijami in RSS identifikatorji postaj
RSS_STATION_CODES = {
    # Opazovalne postaje (observation)
    "Bilje pri Novi Gorici": "observation_NOVA-GOR",
    "Celje": "observation_CELJE",
    "Črnomelj": "observation_CRNOMELJ",
    "Katarina nad Ljubljano": "observation_KATARINA",
    "Kočevje": "observation_KOCEVJE",
    "Kredarica": "observation_KREDA-ICA",
    "Letališče Cerklje ob Krki": "observation_CERKLJE_LETAL-SCE",
    "Letališče Edvarda Rusjana Maribor": "observation_MARIBOR_SLIVNICA",
    "Letališče Jožeta Pučnika Ljubljana": "observation_LJUBL-ANA_BRNIK",
    "Letališče Lesce": "observation_LESCE",
    "Letališče Portorož": "observation_PORTOROZ_SECOVLJE",
    "Lisca": "observation_LISCA",
    "Ljubljana": "observation_LJUBL-ANA_BEZIGRAD",
    "Murska Sobota": "observation_MURSK-SOB",
    "Novo mesto": "observation_NOVO-MES",
    "Postojna": "observation_POSTOJNA",
    "Rateče": "observation_RATECE",
    "Slovenj Gradec": "observation_SLOVE-GRA",
    "Vogel": "observation_VOGEL",
    "Vojsko": "observation_VOJSKO",

    # Samodejne postaje (observationAms)
    "Babno Polje": "observationAms_BABNO-POL",
    "Bilje Nova Gorica": "observationAms_NOVA-GOR",
    "Blegoš": "observationAms_BLEGOS",
    "Bohinjska Češnjica": "observationAms_BOHIN-CES",
    "Boršt Gorenja vas": "observationAms_BORST_GOREN-VAS",
    "Bovec": "observationAms_BOVEC",
    "Breginj": "observationAms_BREGINJ",
    "Bukovski vrh": "observationAms_BUKOV-VRH",
    "Cerkniško jezero": "observationAms_CERKN-JEZ",
    "Davča": "observationAms_DAVCA",
    "Debeli Rtič": "observationAms_DEBEL-RTI",
    "Dobliče Črnomelj": "observationAms_CRNOMELJ",
    "Dolenje Ajdovščina": "observationAms_AJDOV-INA_DOLENJE",
    "Gačnik": "observationAms_GACNIK",
    "Godnje": "observationAms_GODNJE",
    "Gornji Grad": "observationAms_GORNJ-GRA",
    "Hočko Pohorje": "observationAms_HOCKO-POH",
    "Hrastnik": "observationAms_HRASTNIK",
    "Idrija": "observationAms_IDRIJA_CISTI-NAP",
    "Ilirska Bistrica": "observationAms_ILIRS-BIS",
    "Iskrba": "observationAms_ISKRBA",
    "Jeronim": "observationAms_JERONIM",
    "Jeruzalem": "observationAms_JERUZ-LEM",
    "Jezersko": "observationAms_JEZERSKO",
    "Kamniška Bistrica": "observationAms_KAMNI-BIS",
    "Kanin": "observationAms_KANIN",
    "Koper Kapitanija": "observationAms_KOPER_KAPET-IJA",
    "Korensko sedlo": "observationAms_KOREN-SED",
    "Krajinski park Goričko": "observationAms_GORICKO_KRAJI-PAR",
    "Kranj": "observationAms_KRANJ",
    "Krn": "observationAms_KRN",
    "Krvavec": "observationAms_KRVAVEC",
    "Krško": "observationAms_KRSKO_NEK",
    "Kubed": "observationAms_KUBED",
    "Kum": "observationAms_KUM",
    "Lendava": "observationAms_LENDAVA",
    "Logarska dolina": "observationAms_LOGAR-DOL",
    "Logatec": "observationAms_LOGATEC",
    "Malkovec": "observationAms_MALKOVEC",
    "Maribor": "observationAms_MARIBOR_VRBAN-PLA",
    "Marinča vas": "observationAms_MARIN-VAS",
    "Mežica": "observationAms_MEZICA",
    "Metlika": "observationAms_METLIKA",
    "Miklavž na Gorjancih": "observationAms_MIKLAVZ_NA-GOR",
    "Nanos": "observationAms_NANOS",
    "Nova Gorica": "observationAms_NOVA-GOR",
    "Nova vas - Bloke": "observationAms_NOVA-VAS_BLOKE",
    "Osilnica": "observationAms_OSILNICA",
    "Otlica": "observationAms_OTLICA",
    "Park Škocjanske jame": "observationAms_SKOCJAN",
    "Pasja ravan": "observationAms_PASJA-RAV",
    "Pavličevo sedlo": "observationAms_PAVLI-SED",
    "Piran - oceanografska boja": "observationAms_PIRAN_OCEAN-BOJ",
    "Planina pod Golico": "observationAms_PLANI-POD",
    "Podčetrtek": "observationAms_PODCE-TEK_ATOMS-TOP",
    "Podnanos": "observationAms_PODNANOS",
    "Postojna": "observationAms_POSTOJNA",
    "Predel": "observationAms_PREDEL",
    "Ptuj": "observationAms_PTUJ",
    "Radegunda": "observationAms_RADEG-NDA",
    "Rateče": "observationAms_RATECE",
    "Ratitovec": "observationAms_RATIT-VEC",
    "Ravne na Koroškem": "observationAms_RAVNE_NA-KOR",
    "Rogaška Slatina": "observationAms_ROGAS-SLA",
    "Rogla": "observationAms_ROGLA",
    "Rudno polje": "observationAms_RUDNO-POL",
    "Sevno": "observationAms_SEVNO",
    "Slavnik": "observationAms_SLAVNIK",
    "Slovenske Konjice": "observationAms_SLOVE-KON",
    "Sveti Trije Kralji na Pohorju": "observationAms_TRIJE-KRA_NA-POH",
    "Sviščaki": "observationAms_SVISCAKI",
    "Šebreljski vrh": "observationAms_SEBRE-VRH",
    "Šmartno pri Slovenj Gradcu": "observationAms_SLOVE-GRA",
    "Tatre": "observationAms_TATRE",
    "Tolmin - Volče": "observationAms_TOLMIN_VOLCE",
    "Topol": "observationAms_TOPOL",
    "Trbovlje": "observationAms_TRBOVLJE",
    "Trebnje": "observationAms_TREBNJE",
    "Trojane - Limovce": "observationAms_TROJANE_LIMOVCE",
    "Tržaški zaliv": "observationAms_TRZAS-ZAL",
    "Uršlja gora": "observationAms_URSLJ-GOR",
    "Vedrijan": "observationAms_VEDRIJAN",
    "Velenje": "observationAms_VELENJE",
    "Velike Lašče": "observationAms_VELIK-LAS",
    "Vogel": "observationAms_VOGEL",
    "Vrhnika": "observationAms_VRHNIKA",
    "Vršič": "observationAms_VRSIC",
    "Zadlog": "observationAms_ZADLOG",
    "Zelenica": "observationAms_ZELENICA",
    "Zgornja Kapla": "observationAms_ZGORN-KAP",
    "Zgornja Radovna": "observationAms_ZGORN-RAD",
    "Zgornja Sorica": "observationAms_ZGORN-SOR"
}
