name: HassFest

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hassfest:
    name: Run HassFest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run hassfest
        uses: home-assistant/actions/hassfest@main
